type_weaknesses = {
    "normal": [],
    "fire": ["water", "ground", "rock"],
    "water": ["electric", "grass"],
    "electric": ["ground"],
    "grass": ["fire", "ice", "poison", "flying", "bug"],
    "ice": ["fighting", "rock", "steel"],
    "fighting": ["flying", "psychic", "fairy"],
    "poison": ["ground", "psychic"],
    "ground": ["ice", "dragon", "fairy"],
    "flying": ["electric", "ice", "rock"],
    "psychic": ["bug", "ghost", "dark"],
    "bug": ["fire", "flying", "rock"],
    "rock": ["water", "grass", "fighting", "ground", "steel"],
    "ghost": ["ghost", "dark"],
    "dragon": ["ice", "dragon", "fairy"],
    "dark": ["fighting", "bug", "fairy"],
    "steel": ["fire", "fighting", "ground"],
    "fairy": ["poison", "steel"],
    # All possible dual types
    "normal_normal": [],
    "normal_fire": ["water", "ground", "rock"],
    "normal_water": ["electric", "grass"],
    "normal_electric": ["ground"],
    "normal_grass": ["fire", "ice", "poison", "flying", "bug"],
    "normal_ice": ["fighting", "rock", "steel"],
    "normal_fighting": ["flying", "psychic", "fairy"],
    "normal_poison": ["ground", "psychic"],
    "normal_ground": ["ice", "dragon", "fairy"],
    "normal_flying": ["electric", "ice", "rock"],
    "normal_psychic": ["bug", "ghost", "dark"],
    "normal_bug": ["fire", "flying", "rock"],
    "normal_rock": ["water", "grass", "fighting", "ground", "steel"],
    "normal_ghost": ["ghost", "dark"],
    "normal_dragon": ["ice", "dragon", "fairy"],
    "normal_dark": ["fighting", "bug", "fairy"],
    "normal_steel": ["fire", "fighting", "ground"],
    "normal_fairy": ["poison", "steel"],
    "fire_fire": ["water", "ground", "rock"],
    "fire_water": ["electric", "ground", "rock"],
    "fire_electric": ["ground", "rock"],
    "fire_grass": ["water", "ground", "rock"],
    "fire_ice": ["water", "rock", "ground"],
    "fire_fighting": ["water", "ground", "rock"],
    "fire_poison": ["ground", "rock", "psychic"],
    "fire_ground": ["water", "rock", "ground"],
    "fire_flying": ["electric", "rock"],
    "fire_psychic": ["water", "rock", "ground", "dark", "ghost"],
    "fire_bug": ["water", "rock", "ground"],
    "fire_rock": ["water", "ground"],
    "fire_ghost": ["rock", "ground", "water"],
    "fire_dragon": ["rock", "ground", "dragon"],
    "fire_dark": ["rock", "ground", "water", "fighting", "fairy"],
    "fire_steel": ["water", "rock", "ground", "fighting"],
    "fire_fairy": ["rock", "ground", "water", "poison", "steel"],
    "water_water": ["electric", "grass"],
    "water_electric": ["grass"],
    "water_grass": ["electric"],
    "water_ice": ["electric", "grass", "fighting", "rock"],
    "water_fighting": ["electric", "grass"],
    "water_poison": ["electric", "grass", "ground", "psychic"],
    "water_ground": ["grass"],
    "water_flying": ["electric", "grass"],
    "water_psychic": ["electric", "grass", "bug", "ghost", "dark"],
    "water_bug": ["electric", "grass"],
    "water_rock": ["electric", "grass"],
    "water_ghost": ["grass", "electric"],
    "water_dragon": ["grass", "electric", "dragon"],
    "water_dark": ["grass", "electric", "ghost", "bug", "fairy"],
    "water_steel": ["grass", "electric"],
    "water_fairy": ["grass", "electric", "poison", "steel"],
    "electric_electric": ["ground"],
    "electric_grass": ["ground"],
    "electric_ice": ["ground", "rock"],
    "electric_fighting": ["ground"],
    "electric_poison": ["ground"],
    "electric_ground": [],
    "electric_flying": ["ice", "rock"],
    "electric_psychic": ["ground", "rock", "ghost", "dark"],
    "electric_bug": ["rock", "ground"],
    "electric_rock": ["ground"],
    "electric_ghost": ["rock", "ground", "dark"],
    "electric_dragon": ["ground"],
    "electric_dark": ["rock", "ground", "ghost", "fighting", "fairy"],
    "electric_steel": ["fire", "fighting", "ground"],
    "electric_fairy": ["ground", "rock", "poison", "fighting"],
    "grass_grass": ["fire", "ice", "poison", "flying", "bug"],
    "grass_ice": ["fire", "ice", "fighting", "rock", "steel"],
    "grass_fighting": ["fire", "ice", "poison", "flying", "bug"],
    "grass_poison": ["ground", "psychic"],
    "grass_ground": ["ice", "dragon", "fairy"],
    "grass_flying": ["electric", "ice", "rock"],
    "grass_psychic": ["bug", "ghost", "dark"],
    "grass_bug": ["fire", "flying", "rock"],
    "grass_rock": ["water", "grass", "fighting", "ground", "steel"],
    "grass_ghost": ["ghost", "dark"],
    "grass_dragon": ["ice", "dragon", "fairy"],
    "grass_dark": ["fighting", "bug", "fairy"],
    "grass_steel": ["fire", "fighting", "ground"],
    "grass_fairy": ["poison", "steel"],
    "ice_ice": ["fighting", "rock", "steel"],
    "ice_fighting": ["fire", "fighting", "rock", "steel"],
    "ice_poison": ["fighting", "rock", "steel"],
    "ice_ground": ["fighting", "rock", "steel"],
    "ice_flying": ["rock", "steel"],
    "ice_psychic": ["fighting", "rock", "steel", "bug", "ghost", "dark"],
    "ice_bug": ["fighting", "rock", "steel"],
    "ice_rock": ["water", "grass", "fighting", "ground", "steel"],
    "ice_ghost": ["rock", "steel", "fighting", "bug", "fairy"],
    "ice_dragon": ["rock", "steel", "fighting", "bug", "fairy"],
    "ice_dark": ["fighting", "rock", "steel", "ghost", "bug", "fairy"],
    "ice_steel": ["fire", "fighting", "ground"],
    "ice_fairy": ["rock", "steel", "fighting", "bug", "poison"],
    "fighting_fighting": ["flying", "psychic", "fairy"],
    "fighting_poison": ["flying", "psychic", "fairy"],
    "fighting_ground": ["flying", "psychic", "fairy"],
    "fighting_flying": ["psychic", "fairy"],
    "fighting_psychic": ["bug", "ghost", "fairy"],
    "fighting_bug": ["flying", "psychic", "fairy"],
    "fighting_rock": ["flying", "psychic", "fairy"],
    "fighting_ghost": ["flying", "psychic", "fairy"],
    "fighting_dragon": ["flying", "psychic", "fairy"],
    "fighting_dark": ["flying", "psychic", "fairy"],
    "fighting_steel": ["flying", "psychic", "fairy"],
    "fighting_fairy": ["flying", "psychic", "fairy"],
    "poison_poison": ["ground", "psychic"],
    "poison_ground": ["water", "ice", "psychic", "ground", "fairy"],
    "poison_flying": ["electric", "ice", "rock"],
    "poison_psychic": ["ground", "ghost", "dark"],
    "poison_bug": ["fire", "flying", "rock"],
    "poison_rock": ["water", "grass", "fighting", "steel"],
    "poison_ghost": ["ghost", "dark"],
    "poison_dragon": ["ice", "dragon", "fairy"],
    "poison_dark": ["fighting", "bug", "fairy"],
    "poison_steel": ["fire", "fighting", "ground"],
    "poison_fairy": ["poison", "steel"],
    "ground_ground": ["ice", "dragon", "fairy"],
    "ground_flying": ["electric", "ice"],
    "ground_psychic": ["bug", "ghost", "dark"],
    "ground_bug": ["fire", "flying", "rock"],
    "ground_rock": ["water", "grass", "fighting", "steel"],
    "ground_ghost": ["ghost", "dark"],
    "ground_dragon": ["ice", "dragon", "fairy"],
    "ground_dark": ["fighting", "bug", "fairy"],
    "ground_steel": ["fire", "fighting", "ground"],
    "ground_fairy": ["poison", "steel"],
    "flying_flying": ["electric", "ice", "rock"],
    "flying_psychic": ["bug", "ghost", "dark"],
    "flying_bug": ["fire", "rock"],
    "flying_rock": ["electric", "ice"],
    "flying_ghost": ["electric", "ice", "rock"],
    "flying_dragon": ["electric", "ice", "rock"],
    "flying_dark": ["electric", "ice", "rock"],
    "flying_steel": ["electric", "ice", "rock"],
    "flying_fairy": ["electric", "ice", "rock"],
    "psychic_psychic": ["bug", "ghost", "dark"],
    "psychic_bug": ["fire", "flying", "rock"],
    "psychic_rock": ["electric", "ice"],
    "psychic_ghost": ["ghost", "dark"],
    "psychic_dragon": ["ice", "dragon", "fairy"],
    "psychic_dark": ["fighting", "bug", "fairy"],
    "psychic_steel": ["fire", "fighting", "ground"],
    "psychic_fairy": ["bug", "ghost", "dark"],
    "bug_bug": ["fire", "flying", "rock"],
    "bug_rock": ["fire", "flying"],
    "bug_ghost": ["fire", "flying", "rock"],
    "bug_dragon": ["fire", "flying", "rock"],
    "bug_dark": ["flying", "psychic", "fairy"],
    "bug_steel": ["fire", "fighting", "ground"],
    "bug_fairy": ["fire", "flying", "rock"],
    "rock_rock": ["water", "grass", "fighting", "ground", "steel"],
    "rock_ghost": ["ghost", "dark"],
    "rock_dragon": ["ice", "dragon", "fairy"],
    "rock_dark": ["fighting", "bug", "fairy"],
    "rock_steel": ["fire", "fighting", "ground"],
    "rock_fairy": ["poison", "steel"],
    "ghost_ghost": ["ghost", "dark"],
    "ghost_dragon": ["ice", "dragon", "fairy"],
    "ghost_dark": ["fighting", "bug", "fairy"],
    "ghost_steel": ["fire", "fighting", "ground"],
    "ghost_fairy": ["poison", "steel"],
    "dragon_dragon": ["ice", "dragon", "fairy"],
    "dragon_dark": ["fighting", "bug", "fairy"],
    "dragon_steel": ["fire", "fighting", "ground"],
    "dragon_fairy": ["ice", "dragon", "fairy"],
    "dark_dark": ["fighting", "bug", "fairy"],
    "dark_steel": ["fire", "fighting", "ground"],
    "dark_fairy": ["fighting", "bug", "fairy"],
    "steel_steel": ["fire", "fighting", "ground"],
    "steel_fairy": ["poison", "steel"],
    "fairy_fairy": ["poison", "steel"]
}
