weaknesses = {
    "normal": ["fighting"],
    "fire": ["water", "rock"],
    "water": ["electric", "grass"],
    "electric": ["ground"],
    "grass": ["fire"],
    "ice": ["fire"],
    "fighting": ["flying", "psychic"],
    "poison": ["ground", "psychic"],
    "ground": ["water", "grass", "ice"],
    "flying": ["electric", "ice", "rock"],
    "psychic": ["bug", "ghost", "dark"],
    "bug": ["fire", "flying", "rock"],
    "rock": ["water", "grass", "fighting", "ground", "steel"],
    "ghost": ["ghost", "dark"],
    "dragon": ["ice", "dragon", "fairy"],
    "dark": ["fighting", "bug", "fairy"],
    "steel": ["fire", "fighting", "ground"],
    "fairy": ["poison", "steel"],
    "ground/rock": ["water2x", "grass2x", "fighting", "ground", "steel", "ice"],
    "rock/ice": ["fighting", "steel", "ground", "rock", "water", "grass"],
    "bug/grass": ["flying2x", "fire2x", "poison", "rock", "bug", "ice"],
    "rock/fire": ["ground", "water2x", "fighting", "rock"],
    "bug/ice": ["rock", "fire2x", "flying2x", "steel"],
    "rock/steel": ["fighting", "ground", "water2x"],
    "steel/ice": ["fighting", "fire2x", "ground"],
    "ghost/psychic": ["ghost2x", "dark"],
    "rock/dark": ["fighting", "ground", "bug", "steel", "water2x", "grass2x", "fairy"],
    "grass/psychic": ["bug", "flying2x", "poison", "ghost", "fire", "ice", "dark"],
    "grass/ice": ["fire2x", "fighting", "flying", "poison", "rock", "bug", "steel"],
    "grass/dark": ["fire2x", "fighting", "flying", "poison", "rock", "bug", "steel"],
    "fighting/grass": ["flying2x", "poison", "fire", "psychic", "ice", "fairy"],
    "grass/dragon": ["ice2x", "flying", "poison", "bug", "dragon", "fairy"],
    "ice/dark": ["fighting", "rock", "bug", "steel", "fire", "fairy"],
    "normal/rock": ["fighting", "ground", "steel", "water2x", "grass2x"],
    "fighting/dragon": ["fairy2x", "flying", "psychic", "ice", "dragon"],
    "flying/bug": ["rock", "flying", "fire", "electric", "ice"],
    "flying/grass": ["ice2x", "flying", "poison", "rock", "fire"],
    "grass/fairy": ["poison2x", "flying", "steel", "fire", "ice"],
    "dragon/dark": ["fairy2x", "fighting", "bug", "ice", "dragon"],
    "normal/steel": ["fighting", "ground", "fire"],
    "normal/dark": ["fighting", "bug", "fairy"],
    "fighting/poison": ["psychic2x", "flying", "fire", "ground"],
    "fighting/dark": ["fairy2x", "fighting", "flying"],
    "flying/fire": ["rock2x", "water", "electric"],
    "ground/dragon": ["ice2x", "dragon", "fairy"],
    "bug/fire": ["rock", "flying", "water"],
    "steel/fire": ["ground", "fighting", "water"],
    "steel/electric": ["ground", "fighting", "fire"],
    "steel/dark": ["fighting", "ground", "fire"],
    "fire/electric": ["ground", "rock", "water"],
    "flying/ground": ["ice2x", "water"],
    "flying/water": ["electric2x", "rock"],
    "poison/steel": ["ground", "fire", "fighting"],
    "poison/electric": ["ground", "psychic"],
    "ground/fire": ["water2x", "ground"],
    "steel/grass": ["fire2x", "fighting"],
    "psychic/dark": ["bug2x", "fairy"],
    "ground/water": ["grass2x"],
    "normal/flying": ["electric", "ice", "rock"],
    "bug/steel": ["fire2x"],
    "fighting/rock": ["fighting", "ground", "steel", "water2x", "grass2x", "psychic", "fairy"],
    "rock/psychic": ["ground", "bug", "ghost", "steel", "water", "grass", "dark"]
    
}

resistances = {
    "water": ["fire", "water", "ice", "steel"]
}

immunities = {
    "ground": ["electric"],
    "grass/dragon": ["electric"],
    "steel": ["poison"]
}